# Site settings
course_name: CSL7070 Computer Architecture
course_description: "In this course we shall learn the basic principles of computer architectures. Computer architecture is the science and art of selecting and interconnecting hardware components to create a computer that meets functional, performance and cost goals. This course introduces the basic hardware structure of a modern programmable computer, including the basic laws underlying performance evaluation."
course_semester: "Semester II: 2021-22"

baseurl: "/wi22-csl7070" # the subpath of your site, e.g. /blog/
url: "http://dipsankarb.github.io/" # the base hostname & protocol for your site

schoolname: "Department of CSE, IIT Jodhpur"
schoolurl: "https://cse.iitj.ac.in"
twitter_username: dipsankarb 
email: dipsankarb[AT]iitj.ac.in

address: |
    Department of CSE, IIT Jodhpur
    NH 62, Karwar
    Jodhpur 342037
    Rajasthan, India.

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
