# Site settings
course_name: CSL1010 Introduction to Computer Science
course_description: "This subject is aimed at students with little or no programming experience. It aims to provide students with an understanding of the role computation can play in solving problems. It also aims to help students, regardless of their major, to feel justifiably confident of their ability to write small programs that allow them to accomplish useful goals. The class will use the Python™ programming language." 
course_semester: "Semester II: 2021-22"

baseurl: "/wi22-csl1010" # the subpath of your site, e.g. /blog/
url: "http://dipsankarb.github.io/" # the base hostname & protocol for your site

schoolname: "Department of CSE, IIT Jodhpur"
schoolurl: "https://cse.iitj.ac.in"
twitter_username: dipsankarb 
email: dipsankarb[AT]iitj.ac.in

address: |
    Department of CSE, IIT Jodhpur
    NH 62, Karwar
    Jodhpur 342037
    Rajasthan, India.

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
